### PR TITLE
Update to new artifactId and version scheme

### PR DESCRIPTION
**Pull request by kenfinnigan**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Would appreciate your feedback @cescoffier as to whether I've gone too crazy with the MP version suffix on `artifactId`.

Think I did it where it made sense, let me know if that's not the case

**Comment by cescoffier** [comment]
@kenfinnigan can you rebase?

**Comment by kenfinnigan** [comment]
should be fixed now

**Comment by cescoffier** [comment]
Thanks, Waiting for CI

**Comment by cescoffier** [comment]
@kenfinnigan the build fails: 
[ERROR]     Non-resolvable parent POM for io.smallrye.reactive:smallrye-reactive-streams-operators-1.0-release:[unknown-version]: Could not find artifact io.smallrye.reactive:smallrye-reactive-streams-operators-project-1.0:pom:1.0.5-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]

**Comment by kenfinnigan** [comment]
That'll teach me to fix conflicts in the browser!

**Comment by cescoffier** [comment]
Thanks!

**Pull request merged**
